workspace = { members = ["examples/mnist"] }
[package]
name = "bitnet_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candle-core = "0.4.1"
candle-nn = "0.4.1"

